[global]
keyboard = "pl"
country = "pl"
fqdn = "pve.home.arpa"
mailto = "root@localhost"
timezone = "Europe/Warsaw"
root-password-hashed = "REPLACE_WITH_SHA512_CRYPT_HASH"
root-ssh-keys = ["REPLACE_WITH_BOOTSTRAP_SSH_PUBLIC_KEY"]
reboot-mode = "power-off"

[network]
source = "from-answer"
cidr = "10.0.0.50/24"
dns = "1.1.1.1"
gateway = "10.0.0.1"
filter.ID_NET_NAME = "en*"

[disk-setup]
filesystem = "ext4"
filter.ID_BUS = "[!u]*"
