---
- name: Encrypt a controller backup
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  vars_prompt:
    - name: backup_passphrase
      prompt: Controller backup passphrase (retain it for recovery)
      private: true
      confirm: true
  tasks:
    - ansible.builtin.import_tasks: tasks/encrypt-controller.yml
