---
- ansible.builtin.import_playbook: lock.yml
  when: secrets_action | default('status') != 'status'
  any_errors_fatal: true
- ansible.builtin.import_playbook: secrets-init.yml
  any_errors_fatal: true
- ansible.builtin.import_playbook: load-inventory.yml
  when: secrets_action | default('status') == 'rotate'
  any_errors_fatal: true
- ansible.builtin.import_playbook: secrets-run.yml
  any_errors_fatal: true
- ansible.builtin.import_playbook: unlock.yml
  when: secrets_action | default('status') != 'status'
  any_errors_fatal: true
