---
- import_playbook: ready.yml
  any_errors_fatal: true
- import_playbook: baseline.yml
  any_errors_fatal: true
- import_playbook: access.yml
  any_errors_fatal: true

- ansible.builtin.import_playbook: secrets.yml
  vars:
    secrets_action: post-install
  any_errors_fatal: true
